# Generated by Django 4.1.2 on 2022-10-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='emailId',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
